// Code generated by goctl. DO NOT EDIT.
// Source: ai.proto

package userinfo

import (
	"context"

	"AIproto/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserCreateRequest  = __.UserCreateRequest
	UserCreateResponse = __.UserCreateResponse
	UserInfoRequest    = __.UserInfoRequest
	UserInfoResponse   = __.UserInfoResponse

	UserInfo interface {
		UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	}

	defaultUserInfo struct {
		cli zrpc.Client
	}
)

func NewUserInfo(cli zrpc.Client) UserInfo {
	return &defaultUserInfo{
		cli: cli,
	}
}

func (m *defaultUserInfo) UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := __.NewUserInfoClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}
