// Code generated by goctl. DO NOT EDIT.
// Source: ai.proto

package server

import (
	"context"

	"AIproto/internal/logic/userinfo"
	"AIproto/internal/svc"
	"AIproto/proto"
)

type UserInfoServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedUserInfoServer
}

func NewUserInfoServer(svcCtx *svc.ServiceContext) *UserInfoServer {
	return &UserInfoServer{
		svcCtx: svcCtx,
	}
}

func (s *UserInfoServer) UserInfo(ctx context.Context, in *__.UserInfoRequest) (*__.UserInfoResponse, error) {
	l := userinfologic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
