// Code generated by goctl. DO NOT EDIT.
// Source: ai.proto

package server

import (
	"context"

	"AIproto/internal/logic/useraction"
	"AIproto/internal/svc"
	"AIproto/proto"
)

type UserActionServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedUserActionServer
}

func NewUserActionServer(svcCtx *svc.ServiceContext) *UserActionServer {
	return &UserActionServer{
		svcCtx: svcCtx,
	}
}

func (s *UserActionServer) UserCreate(ctx context.Context, in *__.UserCreateRequest) (*__.UserCreateResponse, error) {
	l := useractionlogic.NewUserCreateLogic(ctx, s.svcCtx)
	return l.UserCreate(in)
}
