// Code generated by goctl. DO NOT EDIT.
// Source: ai.proto

package useraction

import (
	"context"

	"AIproto/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserCreateRequest  = __.UserCreateRequest
	UserCreateResponse = __.UserCreateResponse
	UserInfoRequest    = __.UserInfoRequest
	UserInfoResponse   = __.UserInfoResponse

	UserAction interface {
		UserCreate(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error)
	}

	defaultUserAction struct {
		cli zrpc.Client
	}
)

func NewUserAction(cli zrpc.Client) UserAction {
	return &defaultUserAction{
		cli: cli,
	}
}

func (m *defaultUserAction) UserCreate(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error) {
	client := __.NewUserActionClient(m.cli.Conn())
	return client.UserCreate(ctx, in, opts...)
}
